# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.

name: License vetting status check

on:
  push:
    branches: 
      - 'master'
      - 'm2e-*'
  pull_request:
    branches: 
     - 'master'
     - 'm2e-*'

jobs:
  check-licenses:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - run: mvn clean generate-sources -f m2e-maven-runtime/pom.xml -B -Dtycho.mode=maven -Pgenerate-osgi-metadata

    - name: Check license vetting status
      run: mvn -U -B -ntp org.eclipse.dash:license-tool-plugin:license-check -Ddash.fail=true
