# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.

name: License vetting status check

on:
  push:
    branches: 
      - 'master'
      - 'm2e-*'
  pull_request:
    branches: 
     - 'master'
     - 'm2e-*'
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: technology.m2e
      javaVersion: 21
      setupScript: 'cd org.eclipse.m2e.maven.runtime && mvn generate-resources'
    secrets:
      gitlabAPIToken: ${{ secrets.M2E_GITLAB_API_TOKEN }}
