# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.

name: License vetting status check

on:
  push:
    branches: 
      - 'master'
      - 'm2e-*'
  pull_request:
    branches: 
     - 'master'
     - 'm2e-*'
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: technology.m2e
    secrets:
      gitlabAPIToken: ${{ secrets.M2E_GITLAB_API_TOKEN }}
